apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: {{ .Chart.Name }}-internal-api-policy
  namespace: {{ .Values.global.namespace }}
spec:
  targets:
    - name: {{ template "fullname" . }}-internal
  peers:
   - mtls:
      mode: "PERMISSIVE"
---
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: {{ .Chart.Name }}-external-api-policy
  namespace: {{ .Values.global.namespace }}
spec:
  targets:
    - name: {{ template "fullname" . }}
  peers:
    - mtls:
        mode: "PERMISSIVE"
